# Generated by Django 5.0.3 on 2024-06-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proverb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proverb',
            old_name='name',
            new_name='content',
        ),
    ]
